# Generated by Django 4.2.4 on 2023-08-15 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_follower_users_id_alter_following_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='users_id',
        ),
        migrations.RemoveField(
            model_name='following',
            name='users_id',
        ),
        migrations.AddField(
            model_name='follower',
            name='users_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='following',
            name='users_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
