# Generated by Django 4.2.4 on 2023-08-15 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_follower_users_id_remove_following_users_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='users_id',
        ),
        migrations.RemoveField(
            model_name='following',
            name='users_id',
        ),
        migrations.AddField(
            model_name='follower',
            name='users_id',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='following',
            name='users_id',
            field=models.ManyToManyField(related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
