# Generated by Django 4.2.4 on 2023-08-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
