# Generated by Django 4.2.4 on 2023-09-18 06:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='post',
            name='send',
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
