# Generated by Django 4.2.4 on 2023-08-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
