# Generated by Django 4.2.4 on 2023-09-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment_likes_delete_commentlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
