# Generated by Django 4.2.4 on 2023-09-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostOtherAccount',
        ),
    ]
