# Generated by Django 4.2.4 on 2023-08-10 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_location'),
        ('direct', '0002_directmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.following'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.follower'),
        ),
    ]
