# Generated by Django 4.2.4 on 2023-09-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='content',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='user_id',
        ),
    ]
